# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160315_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
